name: aether_nexus
description: Умная экосистема IoT с AI аналитикой
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.19.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  intl: ^0.19.0
  shared_preferences: ^2.0.15



flutter:
  generate: true
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/animations/
    - assets/fonts/

  fonts:
    - family: Exo2
      fonts:
        - asset: assets/fonts/Exo2-Regular.ttf
        - asset: assets/fonts/Exo2-Bold.ttf
          weight: 700

  # localization:
  #   arb-dir: lib/l10n
  #   template-arb-file: app_en.arb
  #   output-localization-file: app_localizations.dart